Repository Lundalogik/lime-elements, pull requests merged in 2020-04, with the labels that each got.

#680 Improve chip styles
  src/components/chip-set/chip-set.scss
Labels: Calamari, Redesign, cooldown

#683 chore: remove `.docz` folder at start of `npm run watch` (and `npm start`)
  package-lock.json
  package.json
Labels: cooldown

#684 Better tabs, inspired by Chrome
  src/components/tab-bar/tab-bar.scss
  src/components/tab-panel/examples/tab-panel.scss
Labels: Calamari, Redesign, cooldown

#698 Adapt lists to new tabs
  src/components/list/list.scss
  src/style/mixins.scss
Labels: Calamari, Redesign, cooldown

#723 fix: prevent argument mismatching in case of value being an array
  src/components/form/templates/array-field-collapsible-item.ts
Labels: Lime Admin 2

#712 fix(chip-set): make chips truncate when their content is too long
  src/components/chip-set/chip-set.scss
Labels: Redesign, bug

#724 fix(form): return descriptive title if title can't be found due to an…
  src/components/form/templates/common.ts
Labels: Lime Admin 2

#726 New props for lists that need striped styles
  src/components/list/examples/list-striped.tsx
  src/components/list/list.mdx
  src/components/list/list.scss
Labels: Redesign, bug
