Repository Lundalogik/lime-elements, pull requests merged in 2021-02, with the labels that each got.

#1114 Table component events
  src/components/table/columns.ts
Labels: Column filters

#1121 docs(button): describe how to color buttons and their labels
  src/components/button/button.tsx
  src/components/button/examples/button-colors.scss
  src/components/button/examples/button-colors.tsx
Labels: docs

#1142 fix(list): border radius on all corners when only 1 item is displayed
  src/components/list/list.scss
Labels: visual design

#1144 docs(popover): fix wrong property name in example
  src/components/popover/examples/popover.scss
Labels: docs

#1155 fix(checkbox): use default material design style for checked state
  src/components/checkbox/checkbox.scss
Labels: usability, visual design
