Repository Lundalogik/lime-elements, pull requests merged in 2022-02, with the labels that each got.

#1548 fix(table): check if tableSelection is exists
  src/components/table/table.tsx
Labels: bug, Select table rows

#1591 fix(badge): don't let it shrink in width, when container is too small
  src/components/badge/badge.scss
Labels: visual design, multi select

#1592 Further improve tabs UI
  src/components/tab-bar/tab-bar.scss
Labels: visual design
