Repository Lundalogik/lime-elements, pull requests merged in 2023-10, with the labels that each got.

#2541 feat(src): export `Link` & `Icon` interfaces
  src/index.ts
Labels: feature

#2551 refactor(icon-button): render tooltip instead of `title` for `label` …
  src/components/icon-button/icon-button.e2e.ts
  src/components/icon-button/icon-button.tsx
Labels: 🦄✨ yolo

#1430 chore(file-viewer): add new component
  src/components/file-viewer/examples/file-viewer-custom-actions.tsx
  src/components/file-viewer/examples/file-viewer-filename.tsx
  src/components/file-viewer/examples/file-viewer-inbuilt-actions.tsx
  src/components/file-viewer/examples/file-viewer-office.tsx
  src/components/file-viewer/examples/file-viewer-with-picker.scss
  src/components/file-viewer/examples/file-viewer-with-picker.tsx
  src/components/file-viewer/examples/file-viewer.scss
  src/components/file-viewer/examples/file-viewer.tsx
  src/components/file-viewer/examples/limel-example-file-viewer-inbuilt-actions.scss
  src/components/file-viewer/extension-mapping.spec.tsx
  src/components/file-viewer/extension-mapping.tsx
  src/components/file-viewer/file-viewer.e2e.ts
  src/components/file-viewer/file-viewer.scss
  src/components/file-viewer/file-viewer.spec.tsx
  src/components/file-viewer/file-viewer.tsx
  src/components/file-viewer/file-viewer.types.ts
  src/components/file-viewer/fullscreen.ts
  src/components/file-viewer/partial-styles/ui-controls.scss
  src/translations/da.ts
  src/translations/en.ts
  src/translations/fi.ts
  src/translations/nl.ts
  src/translations/no.ts
  src/translations/sv.ts
Labels: feature, pot hole

#2558 refactor(icon-button): generate `tooltipId` only once
  src/components/icon-button/icon-button.tsx
Labels: 🦄✨ yolo
