Repository Lundalogik/lime-elements, pull requests merged in 2024-11, with the labels that each got.

#3290 perf(portal): prevent memory leak in internal component used by several components with popovers and dropdowns
  src/components/portal/portal.tsx
Labels: bug, performance

#3308 feat(card): add new component
  etc/lime-elements.api.md
  src/components/card/card.scss
  src/components/card/card.tsx
  src/components/card/examples/card-actions.tsx
  src/components/card/examples/card-basic.scss
  src/components/card/examples/card-basic.tsx
  src/components/card/examples/card-clickable.tsx
  src/components/card/examples/card-image.tsx
  src/components/card/examples/card-nested-component.scss
  src/components/card/examples/card-nested-component.tsx
  src/components/card/examples/card-orientation.tsx
  src/components/card/examples/card-resizable-container.scss
  src/components/card/examples/card-slot.tsx
  src/components/card/examples/card-styling.scss
  src/components/card/examples/card-styling.tsx
Labels: feature

#3328 fix(text-editor): fix bug where html was interpreted as markdown
  package-lock.json
  package.json
  src/components/markdown/markdown-parser.ts
  src/components/text-editor/utils/html-converter.ts
Labels: bug
