Repository Lundalogik/lime-elements, pull requests merged in 2024-09, with the labels that each got.

#3182 perf(portal): do DOM manipulation when portal becomes visible
  src/components/portal/portal.scss
  src/components/portal/portal.tsx
Labels: performance

#3183 perf(form): render collapsed children when they become visible
  src/components/form/templates/array-field-collapsible-item.ts
Labels: performance

#3185 Aria busy info tile
  src/components/info-tile/info-tile.tsx
Labels: accessibility

#3180 fix(progress-flow): increase lock icon visibility
  src/components/progress-flow/progress-flow-item/partial-styles/_selected-indicator.scss
  src/components/progress-flow/progress-flow-item/progress-flow-item.tsx
  src/test-assets/icons/lock.svg
Labels: 🦄✨ yolo
