Repository Lundalogik/lime-elements, pull requests merged in 2024-01, with the labels that each got.

#2720 docs(markdown): add composite example
  src/components/markdown/examples/markdown-composite.scss
  src/components/markdown/examples/markdown-composite.tsx
  src/components/markdown/markdown.tsx
Labels: docs

#2729 Header props
  src/components/header/header.tsx
Labels: 🦄✨ yolo

#2734 feat(action-bar): make `ActionBarItem` generic
  src/components/action-bar/action-bar.types.ts
Labels: activityfeed

#2743 Icon badge header
  src/components/header/header.scss
Labels: 🦄✨ yolo
