Repository Lundalogik/lime-elements, pull requests merged in 2024-05, with the labels that each got.

#2961 fix(text-editor): improve accessibility of `label`
  src/components/text-editor/text-editor.tsx
Labels: accessibility

#2966 fix(text-editor): transition outlines & correctly visualize states
  src/components/text-editor/text-editor.scss
Labels: visual design

#2947 fix(menu): avoid error when `items` is undefined
  src/components/menu-list/menu-list.tsx
Labels: maintenance

#2948 fix(list): avoid error when `items` is undefined
  src/components/list/list.tsx
Labels: bug

#2945 test(table): prevent console.warn logging expected warning to test output
  src/components/table/columns.spec.ts
Labels: maintenance

#2946 test(file-viewer): avoid some console errors and exclude one expected error from test output
  src/components/file-viewer/file-viewer.e2e.ts
  src/test-assets/misc-files/Gorilla-SoundBible.com-1576451741.mp3
  src/test-assets/misc-files/file.pdf
  src/test-assets/misc-files/file.txt
  src/test-assets/misc-files/service-pnp-pga-07100-07149_150px.gif
Labels: maintenance

#2996 UI improvements in chip
  src/components/chip/chip.scss
  src/components/chip/chip.tsx
Labels: usability, visual design
