Repository Lundalogik/lime-elements, pull requests merged in 2025-04, with the labels that each got.

#3532 fix(input-field): ensure label is vertically center aligned, in dialog
  src/components/notched-outline/notched-outline.scss
Labels: visual design, 🦄✨ yolo

#3539 fix(text-editor): ensure a tall `readonly` editor does not overflow its container
  src/components/text-editor/text-editor.scss
Labels: bug

#3513 docs(dialog): add an option field to the form example
  src/components/dialog/examples/dialog-form.tsx
Labels: docs, maintenance, 🦄✨ yolo
